version: '3'

services:
  api:
      build:
        context: ./api
      volumes:
        - ./downloads:/downloads
        - ./api:/app
        - ./logs:/app/logs
      environment:
        - FLASK_ENVIRONMENT=prod
        - POSTGRES_HOST=db
      env_file:
        - ./.env
      depends_on:
        - db
      restart: on-failure:3

  ui:
      build:
        context: ./ui
      volumes:
        - ./ui:/app
      environment:
        - API_URL=/api
      env_file:
        - ./.env
      restart: on-failure:3

  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: on-failure:3
